version: '2'

services:

    base:
        build: .
        ports:
            - "80:80"
        environment:
            DATABASE_URL: "postgresql://postgres:password@db/app_dev"
            APP_SETTINGS: "config.DevelopmentConfig"
        volumes:
            - ./app:/var/www/app
            - ./log:/var/log/app
        depends_on:
            - "db"

    db:
        image: "postgres:alpine"
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: password
        volumes:
            - ./db:/var/lib/postgresql/data
