version: '3'

services:

    base:
        build: .
        environment:
            DATABASE_URL: "postgresql://postgres:password@db/app_dev"
            APP_SETTINGS: "config.DevelopmentConfig"
        volumes:
            - ./app:/var/www/app
            - wsgi-socket-volume:/tmp/uwsgi
        depends_on:
            - "nginx"
            - "db"

    nginx:
        build: nginx
        ports:
            - "80:80"
        volumes:
            - ./app/static:/var/www/static:ro
            - wsgi-socket-volume:/tmp/uwsgi

    db:
        image: "postgres:alpine"
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: password
        volumes:
            - db-data-volume:/var/lib/postgresql/data

volumes:
    db-data-volume:
    wsgi-socket-volume:
