version: '3'

volumes:

    db-data-volume:
    wsgi-socket-volume:

services:

    base:
        build: .
        environment:
            DATABASE_URL: "postgresql://postgres:password@db/flaskapp"
            APP_SETTINGS: "config.DevelopmentConfig"
        volumes:
            - ./app:/var/www/app
            - wsgi-socket-volume:/tmp/uwsgi
        depends_on:
            - "nginx"
            - "db"

    nginx:
        build: nginx
        environment:
            - VIRTUAL_HOST=flaskapp.test
        ports:
            - "7780:80"
        volumes:
            - ./app/static:/var/www/static:ro
            - wsgi-socket-volume:/tmp/uwsgi

    db:
        image: "postgres:alpine"
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: password
        volumes:
            - db-data-volume:/var/lib/postgresql/data

    dnsmasq:
        image: andyshinn/dnsmasq:2.75
        command: "-A /test/127.0.0.1 --log-facility=-"
        ports:
            - "53:53/udp"
            - "53:53/tcp"
        depends_on:
            - nginx-proxy
        cap_add:
            - NET_ADMIN

    nginx-proxy:
        image: jwilder/nginx-proxy
        ports:
            - "80:80"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
